{{- if .Values.promxy.gateway.enabled }}
{{- with .Values.promxy.gateway.httpRoute -}}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $.Release.Name }}-promxy
spec:
  {{- .spec | toYaml | nindent 4 }}
{{- end -}}
{{- end -}}
