{{- $global := .Values.global | default (dict "image" dict) }}
{{- if .Values.victoriametrics.enabled }}
{{- if .Values.victoriametrics.vmalert.enabled }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: cluster
  namespace: {{ .Release.Namespace }}
spec:
  {{- $spec := deepCopy .Values.victoriametrics.vmalert.spec }}
  {{- if not $spec.remoteRead.url }}
  {{- $_ := set $spec.remoteRead "url" (printf "http://vmselect-cluster.%s.svc:8481/select/0/prometheus" .Release.Namespace) }}
  {{- end }}
  {{- if not $spec.remoteWrite.url }}
  {{- $_ := set $spec.remoteWrite "url" (printf "http://vminsert-cluster.%s.svc:8480/insert/0/prometheus/api/v1/write" .Release.Namespace) }}
  {{- end }}
  {{- if not $spec.datasource.url }}
  {{- $_ := set $spec.datasource "url" (printf "http://vmselect-cluster.%s.svc:8481/select/0/prometheus" .Release.Namespace) }}
  {{- end }}
  {{- toYaml $spec | nindent 2 }}
{{- end }}
{{- end }}
