apiVersion: v2
name: kof-mothership
description: KOF Helm chart for KOF Management cluster
version: "1.8.0-rc0"
appVersion: "1.8.0-rc0"
dependencies:
  - name: cluster-api-visualizer
    version: "1.4.0"
    repository: "oci://ghcr.io/k0rdent/cluster-api-visualizer/charts"
    condition: cluster-api-visualizer.enabled
  - name: dex
    version: "0.23.0"
    repository: https://charts.dexidp.io
    condition: dex.enabled
  - name: kgst
    alias: cert-manager-service-template
    version: "1.2.0"
    repository: oci://ghcr.io/k0rdent/catalog/charts
    condition: cert-manager-service-template.enabled
  - name: kgst
    alias: ingress-nginx-service-template
    version: "1.2.0"
    repository: oci://ghcr.io/k0rdent/catalog/charts
  - name: kof-dashboards
    condition: grafana.enabled
    version: "1.8.0-rc0"
    repository: file://../kof-dashboards/
  - name: metrics-server
    version: "3.12.1"
    repository: https://kubernetes-sigs.github.io/metrics-server/
    condition: metrics-server.enabled
