apiVersion: v2
name: kof-mothership
description: KOF Helm chart for KOF Management cluster
version: "1.5.0"
appVersion: "1.5.0"
dependencies:
  - name: victoria-metrics-operator
    version: "0.43.1"
    repository: "https://victoriametrics.github.io/helm-charts/"
    condition: victoria-metrics-operator.enabled
  - name: cluster-api-visualizer
    version: "1.4.0"
    repository: "oci://ghcr.io/k0rdent/cluster-api-visualizer/charts"
    condition: cluster-api-visualizer.enabled
  - name: dex
    version: "0.23.0"
    repository: https://charts.dexidp.io
    condition: dex.enabled
  - name: kgst
    alias: cert-manager-service-template
    version: "1.2.0"
    repository: oci://ghcr.io/k0rdent/catalog/charts
    condition: cert-manager-service-template.enabled
  - name: kgst
    alias: ingress-nginx-service-template
    version: "1.2.0"
    repository: oci://ghcr.io/k0rdent/catalog/charts
  - name: kof-dashboards
    condition: grafana.enabled
    version: "1.5.0"
    repository: file://../kof-dashboards/
