cert-manager:
  enabled: true
  template: cert-manager-v1-16-4

ingress-nginx:
  enabled: true
  template: ingress-nginx-4-12-1

globalValues: {}
collectors: {}
storage: {}
operators: {}

istio:
  # -- Installs resources required for the KOF to work properly with the main Istio chart.
  enabled: true

  dependsOn:
    - k0rdent-istio-network
