cert-manager:
  enabled: true
  template: cert-manager-v1-16-4

ingress-nginx:
  enabled: true
  template: ingress-nginx-4-12-1

collectors: {}
storage: {}
operators: {}

istioMcs:
  # By default, the release name of the Istio chart is "k0rdent-istio".
  # If you are using a different release name, change the prefix of it in the dependsOn list.
  # Otherwise, the MCS will not depend on the Istio installation and might be created before Istio.
  dependsOn:
    - k0rdent-istio-network