apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-kof-downstream-cluster-stats
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-kof-downstream-cluster-stats
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-cluster-stats-collector
  namespace: {{ .Release.Namespace }}
