{{- if .Values.kcm.kof.operator.ui.gateway.enabled }}
{{- with .Values.kcm.kof.operator.ui.gateway.httpRoute -}}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $.Release.Name }}-kof-operator-ui
spec:
  {{- .spec | toYaml | nindent 4 }}
{{- end -}}
{{- end -}}
