{{- if and .Values.dex.enabled .Values.dex.gateway.enabled }}
{{- with .Values.dex.gateway.httpRoute -}}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $.Release.Name }}-dex
spec:
  {{- .spec | toYaml | nindent 4 }}
{{- end -}}
{{- end -}}
