{{- if .Values.gatewayClass.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ .Values.gatewayClass.name }}
spec:
  controllerName: {{ .Values.gatewayClass.controllerName }}
{{- end }}
{{- if .Values.gateway.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  {{- with .Values.gateway.annotations }}
  annotations: {{ . | toYaml | nindent 4 }}
  {{- end }}
spec: {{- .Values.gateway.spec | toYaml | nindent 4 }}
{{- end }}
