{{- if and .Values.victoriametrics.enabled .Values.victoriametrics.vmalert.enabled }}
{{- $global := .Values.global | default dict }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: {{ .Release.Name }}-record-vmrules-executor
  namespace: {{ .Release.Namespace }}
spec:
  {{- .Values.victoriametrics.vmalert.spec | toYaml | nindent 2 }}
{{- end }}
