{{- $global := .Values.global | default dict }}
{{- if .Values.victoriametrics.enabled }}
{{- if .Values.victoriametrics.vmalert.enabled }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanager
metadata:
  name: cluster
  namespace: {{ .Release.Namespace }}
spec:
  {{- .Values.victoriametrics.vmalert.manager.spec | toYaml | nindent 2 }}
{{- end }}
{{- end }}
