{{- if .Values.victoriametrics.enabled }}
{{- if .Values.victoriametrics.vmcluster.enabled }}
{{- if .Values.istio_endpoints }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.clusterName }}-vmauth
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: 8427
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/instance: cluster
    app.kubernetes.io/name: vmauth
{{- end }}
{{- end }}
{{- end }}
