name: PR Conventional Commit Validation

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  validate-pr-title:
    runs-on: ${{ github.repository_owner == 'k0rdent' && 'arc-runner-set-k0rdent' || 'ubuntu-latest' }}
    steps:
      - name: PR Conventional Commit Validation
        uses: ytanikin/pr-conventional-commits@1.4.1
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","perf","chore","revert"]'
          add_label: "false"
