name: Test Helm Charts on KOF

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
      - release/*
    paths:
      - "kof-operator/**"
      - "charts/**"
      - "!**.md"

jobs:
  test:
    name: Run Unit Tests
    runs-on: ${{ github.repository_owner == 'k0rdent' && 'kof' || 'ubuntu-latest' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: ./.github/actions/shared-setup
      - name: Fetch PR Ref and Checkout Repo
        uses: ./.github/actions/fetch-pr-ref
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: kof-operator/go.mod
          cache-dependency-path: kof-operator/go.sum
      - name: Run Unit Tests
        working-directory: ./kof-operator
        run: make test

  lint-react:
    name: Run React Linter
    runs-on: ${{ github.repository_owner == 'k0rdent' && 'kof' || 'ubuntu-latest' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: ./.github/actions/shared-setup
      - name: Fetch PR Ref and Checkout Repo
        uses: ./.github/actions/fetch-pr-ref
      - name: Install dependencies
        working-directory: ./kof-operator/webapp/collector
        run: npm i
      - name: Run ESLint
        working-directory: ./kof-operator/webapp/collector
        run: npm run lint -- --max-warnings=0
      - name: Audit packages
        working-directory: ./kof-operator/webapp/collector
        run: npm audit --audit-level moderate

  ui-tests:
    name: Run React Tests
    runs-on: ${{ github.repository_owner == 'k0rdent' && 'kof' || 'ubuntu-latest' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: ./.github/actions/shared-setup
      - name: Fetch PR Ref and Checkout Repo
        uses: ./.github/actions/fetch-pr-ref
      - name: Install dependencies
        working-directory: ./kof-operator/webapp/collector
        run: npm i
      - name: Run Tests
        working-directory: ./kof-operator/webapp/collector
        run: npm test -- --silent

  deploy:
    name: Deploy KOF & KCM
    runs-on: ${{ github.repository_owner == 'k0rdent' && 'kof' || 'ubuntu-latest' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: ./.github/actions/shared-setup
      - name: Fetch PR Ref and Checkout Repo
        uses: ./.github/actions/fetch-pr-ref
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: kof-operator/go.mod
          cache-dependency-path: kof-operator/go.sum
      - id: kcm_release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: k0rdent
          repo: kcm
          excludes: prerelease, draft
      - name: Checkout KCM Latest Release repo
        uses: actions/checkout@v4
        with:
          repository: k0rdent/kcm
          ref: ${{ steps.kcm_release.outputs.release }}
          path: kcm-repo
      - name: Restore KCM CLI Cache
        id: cache-kcm-cli
        uses: actions/cache/restore@v4
        with:
          path: kcm-repo/bin
          key: kcm-cli-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            kcm-cli-${{ runner.os }}-
      - name: Install KCM CLI
        run: |
          make -C kcm-repo cli-install
      - name: Save KCM CLI Cache
        uses: actions/cache/save@v4
        with:
          path: kcm-repo/bin
          key: kcm-cli-${{ runner.os }}-${{ github.sha }}-${{ github.run_id }}
      - name: Apply KCM Dev Configuration
        run: |
          export KIND_CONFIG_PATH=$PWD/config/kind.yaml
          make -C kcm-repo dev-apply
      - name: Install KOF CLI
        run: |
          make cli-install
      - name: Deploy local registry container
        run: |
          make registry-deploy
      - name: Push KOF Helm Charts
        run: |
          make helm-push
      - name: Deploy KOF Components
        run: |
          make dev-operators-deploy
          make dev-ms-deploy
          make dev-storage-deploy
          make dev-collectors-deploy
