name: Test Adopted Clusters Upgrade

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
      - release/*
    paths:
      - "charts/**"
      - "!**.md"
jobs:
  latest_releases:
    strategy:
      fail-fast: false
      matrix:
        target: ["kcm", "kof", "istio"]
    name: Get Latest Release
    runs-on: ${{ github.repository_owner == 'k0rdent' && 'kof' || 'ubuntu-latest' }}
    steps:
      - id: release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: k0rdent
          repo: ${{ matrix.target }}
          excludes: prerelease, draft
      - name: output
        id: output
        run: |
          echo "${{ matrix.target }}=${{ steps.release.outputs.release }}" >> $GITHUB_OUTPUT
    outputs:
      kcm: ${{ steps.output.outputs.kcm }}
      kof: ${{ steps.output.outputs.kof }}
      istio: ${{ steps.output.outputs.istio }}
  deploy:
    needs: latest_releases
    strategy:
      fail-fast: false
      matrix:
        target: ["dev", "dev-istio"]
    name: Upgrade KOF
    runs-on: ${{ github.repository_owner == 'k0rdent' && 'kof' || 'ubuntu-latest' }}
    steps:
      - name: "[PR] Checkout"
        uses: actions/checkout@v5
      - name: "[PR] Shared setup"
        uses: ./.github/actions/shared-setup
      - name: "[Latest KOF Release] Checkout"
        uses: actions/checkout@v5
        with:
          repository: k0rdent/kof
          ref: ${{ needs.latest_releases.outputs.kof }}
          fetch-depth: 0
      - name: "[Latest KCM Release] Checkout"
        uses: actions/checkout@v5
        with:
          repository: k0rdent/kcm
          ref: ${{ needs.latest_releases.outputs.kcm }}
          path: kcm-repo
          fetch-depth: 0
      - name: "[Latest Istio Release] Checkout"
        if: ${{ matrix.target == 'dev-istio' }}
        uses: actions/checkout@v5
        with:
          repository: k0rdent/istio
          ref: ${{ needs.latest_releases.outputs.istio }}
          path: istio-repo
          fetch-depth: 0
      - name: "[Latest KCM Release] Go version"
        id: latest-kcm-go-version
        uses: arnested/go-version-action@v1
        with:
          working-directory: kcm-repo
      - name: "[Latest KCM Release] Setup Go"
        uses: actions/setup-go@v6
        with:
          go-version-file: kcm-repo/go.mod
          cache-dependency-path: kcm-repo/go.sum
      - name: "[Latest KCM Release] Restore CLI Cache"
        uses: actions/cache/restore@v4
        with:
          path: kcm-repo/bin
          key: kcm-cli-${{ runner.os }}-${{ needs.latest_releases.outputs.kcm }}
          restore-keys: |
            kcm-cli-${{ runner.os }}-
      - name: "Restore Docker Cache"
        uses: actions/cache/restore@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker
      - name: "[Latest KCM Release] Install CLI"
        run: |
          make -C kcm-repo cli-install
      - name: "[Latest KCM Release] Save CLI Cache"
        uses: actions/cache/save@v4
        with:
          path: kcm-repo/bin
          key: kcm-cli-${{ runner.os }}-${{ steps.kcm_release.outputs.release }}-${{ github.run_id }}
      - name: Patch Kind Config
        if: github.repository_owner == 'k0rdent'
        uses: ./.github/actions/kind-config-patch
        with:
          registry-username: ${{ secrets.REGISTRY_CI_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_CI_PASSWORD }}
      - name: "[Latest Release] Install KOF CLI"
        run: |
          make cli-install
      - name: "[Latest KCM Release] Create KIND cluster"
        # TODO: Remove resource limits patch after next KOF release
        run: |
          make kcm-dev-apply KCM_REPO_PATH="kcm-repo" KIND_CONFIG_PATH="$PWD/config/kind.yaml"
          kubectl patch mgmt/kcm --type='json' -p '[{"op": "replace", "path": "/spec/providers", "value":[{"name":"projectsveltos"}]}]'
          kubectl patch mgmt kcm --type=merge -p '{"spec":{"core":{"kcm":{"config":{"resources":{"limits":{"cpu":"500m","memory":"512Mi"},"requests":{"cpu":"10m","memory":"64Mi"}}}}}}}'
          kubectl wait --for=condition=Ready mgmt/kcm --timeout=10m
      - name: "[Latest KOF Release] Deploy local registry"
        run: |
          make registry-deploy
      - name: "[Latest KOF Release] Push Helm Charts"
        run: |
          make helm-push
      - name: "[Latest Istio Release] Go version"
        if: ${{ matrix.target == 'dev-istio' }}
        id: latest-istio-go-version
        uses: arnested/go-version-action@v1
        with:
          working-directory: istio-repo/istio-operator
      - name: "[Latest Istio Release] Setup Go"
        if: ${{ matrix.target == 'dev-istio' && steps.latest-kcm-go-version.outputs.go-mod-version != steps.latest-istio-go-version.outputs.go-mod-version }}
        uses: actions/setup-go@v6
        with:
          go-version-file: istio-repo/istio-operator/go.mod
          cache-dependency-path: istio-repo/istio-operator/go.sum
      - name: "[Latest Istio Release] Install Istio"
        if: ${{ matrix.target == 'dev-istio' }}
        run: |
          kubectl wait --for create crd/clusterprofiles.config.projectsveltos.io --timeout=5m
          kubectl create namespace kof
          kubectl label namespace kof istio-injection=enabled
          make -C istio-repo cli-install
          make -C istio-repo registry-deploy
          make -C istio-repo helm-push
          make -C istio-repo dev-istio-deploy
      - name: "[Latest KOF Release] Go version"
        id: latest-kof-go-version
        uses: arnested/go-version-action@v1
        with:
          working-directory: kof-operator
      - name: "[Latest KOF Release] Setup Go"
        uses: actions/setup-go@v6
        with:
          go-version-file: kof-operator/go.mod
          cache-dependency-path: kof-operator/go.sum
      - name: "[Latest KOF Release] Deploy KOF Components"
        run: |
          make dev-operators-deploy
          make dev-ms-deploy
      - name: "[Latest KOF Release] Cleanup kind clusters if any"
        run: |
          make dev-adopted-rm KIND_CLUSTER_NAME=child-adopted
          make dev-adopted-rm KIND_CLUSTER_NAME=regional-adopted

      - name: "[Latest KOF Release] Run KIND kof Regional cluster"
        run: |
          make dev-adopted-deploy KIND_CLUSTER_NAME=regional-adopted KIND_CONFIG_PATH=$PWD/config/kind.yaml
      - name: Run KIND cloud provider
        run: docker run -d --rm --network kind -v /var/run/docker.sock:/var/run/docker.sock registry.k8s.io/cloud-provider-kind/cloud-controller-manager:v0.7.0
      - name: "[Latest KOF Release] Deploy KOF components on adopted Regional cluster"
        run: |
          make ${{ matrix.target }}-regional-deploy-adopted

      - name: "[Latest KOF Release] Run KIND KOF Child cluster"
        run: |
          make dev-adopted-deploy KIND_CLUSTER_NAME=child-adopted KIND_CONFIG_PATH=$PWD/config/kind.yaml
      - name: "[Latest KOF Release] Configure CoreDNS hosts on Child cluster"
        if: ${{ matrix.target == 'dev' }}
        run: |
          make dev-coredns
      - name: "[Latest KOF Release] Deploy KOF components on adopted Child cluster"
        run: |
          make ${{ matrix.target }}-child-deploy-adopted

      - name: Fetch PR Ref and Checkout Repo
        uses: ./.github/actions/fetch-pr-ref
      - name: "[Main KCM Branch] Checkout KCM repository"
        uses: actions/checkout@v5
        with:
          repository: k0rdent/kcm
          ref: ${{ env.KCM_NEXT_RELEASE }}
          path: kcm-repo
          fetch-depth: 0
      - name: "[Main KCM Branch] Go version"
        id: main-kcm-go-version
        uses: arnested/go-version-action@v1
        with:
          working-directory: kcm-repo
      - name: "[Main KCM Branch] Setup Go"
        if: ${{ steps.latest-kof-go-version.outputs.go-mod-version != steps.main-kcm-go-version.outputs.go-mod-version }}
        uses: actions/setup-go@v6
        with:
          go-version-file: kcm-repo/go.mod
          cache-dependency-path: kcm-repo/go.sum
      - name: "[Main KCM Branch] Install CLI"
        run: |
          make -C kcm-repo cli-install
      - name: "[Main KCM Branch] Upgrade KCM"
        run: |
          make kcm-dev-upgrade KCM_REPO_PATH="kcm-repo"
          kubectl patch mgmt/kcm --type='json' -p '[{"op": "replace", "path": "/spec/providers", "value":[{"name":"projectsveltos"}]}]'
      - name: "[PR] Install KOF CLI"
        run: |
          make cli-install
      - name: "[PR] Push KOF Helm Charts"
        run: |
          make helm-push
      - name: "[Main Istio Branch] Checkout"
        if: ${{ matrix.target == 'dev-istio' }}
        uses: actions/checkout@v5
        with:
          repository: k0rdent/istio
          ref: main
          path: istio-repo
          fetch-depth: 0
      - name: "[Main Istio Branch] Go version"
        if: ${{ matrix.target == 'dev-istio' }}
        id: main-istio-go-version
        uses: arnested/go-version-action@v1
        with:
          working-directory: istio-repo/istio-operator
      - name: "[Main Istio Branch] Setup Go"
        if: ${{ matrix.target == 'dev-istio' && steps.main-istio-go-version.outputs.go-mod-version != steps.main-kcm-go-version.outputs.go-mod-version }}
        uses: actions/setup-go@v6
        with:
          go-version-file: istio-repo/istio-operator/go.mod
          cache-dependency-path: istio-repo/istio-operator/go.sum
      - name: "[Main Istio Branch] Install Istio"
        if: ${{ matrix.target == 'dev-istio' }}
        run: |
          make -C istio-repo cli-install
          make -C istio-repo registry-deploy
          make -C istio-repo helm-push
          make -C istio-repo dev-istio-deploy
      - name: "[Main Branch] KOF Go version"
        id: main-kof-go-version
        uses: arnested/go-version-action@v1
        with:
          working-directory: kof-operator
      - name: "[Main Branch] Setup Go"
        uses: actions/setup-go@v6
        with:
          go-version-file: kof-operator/go.mod
          cache-dependency-path: kof-operator/go.sum
      - name: "[PR] Deploy KOF components on Mothership cluster"
        run: |
          make dev-operators-deploy
          make dev-ms-deploy
      - name: "[PR] Run KIND kof Regional cluster"
        run: |
          make dev-adopted-deploy KIND_CLUSTER_NAME=regional-adopted KIND_CONFIG_PATH=$PWD/config/kind.yaml
      - name: "[PR] Run KIND kof Child cluster"
        run: |
          make dev-adopted-deploy KIND_CLUSTER_NAME=child-adopted KIND_CONFIG_PATH=$PWD/config/kind.yaml
      
      # TODO Remove label patch after next KOF release
      - name: "[PR] Deploy KOF components on adopted Regional cluster"
        run: |
          make ${{ matrix.target }}-regional-deploy-adopted
          kubectl patch cld/regional-adopted -n kcm-system --type=merge -p '{"metadata":{"labels":{"k0rdent.mirantis.com/kof-cluster-name":"regional-adopted"}}}'
      - name: "[PR] Deploy KOF components on adopted Child cluster"
        run: |
          make ${{ matrix.target }}-child-deploy-adopted
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
      - run: pip install -r scripts/requirements.txt
      - name: Waiting 10m for metrics collection
        run: sleep 10m
      - run: make dev-promxy-port-forward
      - name: Checking promxy metrics
        run: ./scripts/metrics.py
      - name: Make support-bundle
        if: ${{ failure() }}
        run: |
          make support-bundle
          make support-bundle KUBECTL_CONTEXT=kind-regional-adopted
          make support-bundle KUBECTL_CONTEXT=kind-child-adopted
      - name: Archive support-bundle
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-support-bundles.tar.gz
          path: ./support-bundle-*.tar.gz
